### ISSUE TITLE
Running rails test in bin/open getting this error

### ISSUE THREAD

**Issue by ronald2wing** [the-teacher/rails7-startkit#53]
`lucky@55409a6028c4:~/app$ rails test
<internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load
 such file -- test_helper (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:
in `require'
        from /home/lucky/app/test/models/user_test.rb:3:in `<main>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:
in `require'
        from /usr/local/bundle/gems/railties-7.0.7.2/lib/rails/test_unit/runner.rb:47:in `block in load_tests'
        from /usr/local/bundle/gems/railties-7.0.7.2/lib/rails/test_unit/runner.rb:47:in `each'
        from /usr/local/bundle/gems/railties-7.0.7.2/lib/rails/test_unit/runner.rb:47:in `load_tests'
        from /usr/local/bundle/gems/railties-7.0.7.2/lib/rails/test_unit/runner.rb:40:in `run'
        from /usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands/test/test_command.rb:33:in `perform'
        from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-7.0.7.2/lib/rails/command/base.rb:87:in `perform'
        from /usr/local/bundle/gems/railties-7.0.7.2/lib/rails/command.rb:48:in `invoke'
        from /usr/local/bundle/gems/railties-7.0.7.2/lib/rails/commands.rb:18:in `<main>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:
in `require'
        from bin/rails:6:in `<main>'
`

Removing require 'test_helper' in test/models/user_test.rb will fix the problem.

**Comment by ronald2wing** [comment]
Test will work with bin/exec rspec.
